---
version: '3.8'
volumes:
  jackett_config: {}
  redis_data: {}

services:
  annatar:
    image: registry.gitlab.com/stremio-add-ons/annatar:latest
    ports:
      - "8000:8000"
    depends_on:
      - jackett
    volumes:
      - "redis_data:/app/data"
    environment:
      LOG_LEVEL: debug
      JACKETT_URL: "https://mikmc-jackett.elfhosted.com"
      JACKETT_API_KEY: "pr3hehabdz8xz605svarhpeel4t38slm"
      JACKETT_MAX_RESULTS: "100" # max results from jackett search
      JACKETT_TIMEOUT: "60" # max time spent searching per indexer.
      JACKETT_INDEXERS: "aither-api,bitsearch,concen,digitalcore,extremlymtorrents,hawke-uno,morethantv-api,skipthetrailers,solidtorrents,torrentseeds-api,torrentz2nz,tvchaosuk,xtremebytes"
      LISTEN_PORT: "8000"

  jackett:
    image: docker.io/linuxserver/jackett
    ports:
      - 9117:9117
    volumes:
      - jackett_config:/config
