---
version: '3.8'
volumes:
  jackett_config: {}
  redis_data: {}

services:
  annatar:
    image: registry.gitlab.com/stremio-add-ons/annatar:latest
    ports:
      - "8000:8000"
    depends_on:
      - jackett
    volumes:
      - "redis_data:/app/data"
    environment:
      LOG_LEVEL: debug
      JACKETT_URL: "http://195.154.231.70:9117"
      JACKETT_API_KEY: "ar2u3emdwocp9cqcbyiugot0t17s65yl"
      JACKETT_MAX_RESULTS: "100" # max results from jackett search
      JACKETT_TIMEOUT: "60" # max time spent searching per indexer.
      JACKETT_INDEXERS: "aither-api,avistaz,bitsearch,bwtorrents,digitalcore,filelist,greatposterwall,morethantv-api,privatehd,rutracker,skipthetrailers,solidtorrents,torrentleech,torrentseeds-api"
      LISTEN_PORT: "8000"

  jackett:
    image: docker.io/linuxserver/jackett
    ports:
      - 9117:9117
    volumes:
      - jackett_config:/config
